import Provider from './components/Provider'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode,
}){
  return (
    <html
      lang='en'
      className={`${inter.className} h-full scroll-smooth antialiased`}
    >
      <body className='flex h-full flex-col'>
        <div>ef43f34gf34gf4fg34f34f</div>
        <Provider>
          <main className='grow'>{children}</main>
        </Provider>
        <div>f3qe4gf43ferf</div>
      </body>
    </html>
  )
}